#!/usr/bin/env python3

import sys
from PyQt5 import QtWidgets
from libjustplot import MainWindow

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec()
